#!/usr/bin/env bash
# surrogate full backup function using mysqldump
dump_err=0
:> $surr_full_status

perform_action() {
instance=$1
if [ -z "$socket" ]; then
	socket_variable=mysql_socket_${instance}
	socket=${!socket_variable}
fi

# Determine full_backup_path based on day of week and day of month
determine_full_backup_path
mkdir -p $full_backup_path
## experimental backup log output 
copy_out $full_backup_path/surrogate.log
echo $full_backup_path/surrogate.log | awk -v brh=$backup_report_host -v h=$server -F "/backup" '{print "<a href="brh"/"h$2">View Log File</a>"}' >> $surr_full_status
##
dblist=`mysql -u $mysql_user -p${mysql_pass} -S $mysql_socket -se "show databases"  | grep -v ^Database$ | grep -v ^information_schema$`
catch $surr_full_status
for database in $dblist; do
	update_vars
	echo $dump_backup
       	eval $dump_backup
	# check $? and update status file accordingly
	catch $surr_full_status
done
}
